version: "3.9"

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api-gateway:
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
    volumes:
      - ./api_gateway:/app
    env_file:
      - .env
    depends_on:
      - redis
    ports:
      - "8000:8000"

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    volumes:
      - ./worker:/app
    env_file:
      - .env
    depends_on:
      - redis